### ISSUE TITLE
Reliant on ovos-workshop 0.0.3a1 => breaks various other skills of yours

### ISSUE THREAD

**Issue by theCalcaholic** [JarbasSkills/skill-sovietwave#3]
So, in order to comply to the new requirements.txt, I installed ovos-workshop from master (because 0.0.3a1 is not available on pipy yet).

Unfortunately, this broke some other skills of yours (disregarding the fact that automatic installation won't work):

- [skill-simple-youtube](https://github.com/JarbasSkills/skill-simple-youtube) crashes, because some imports don't work anymore as they used to (easy to fix though). I'll create a separate issue on the simple-youtube skill for that.
- ~~[skill-better-playback-control](https://github.com/OpenVoiceOS/skill-better-playback-control) crashes due to multiple reasons.~~ Turns out I didn't have the latest version installed. It appears to work fine now :)

<!--Since issues are disabled on the github project, I'll describe everything related to it in detail:~~
  - Similarly to skill-simple-youtube, some imports need to be adjusted:
  ```diff
  -from ovos_workshop.frameworks.cps import CPSMatchType, CPSPlayback, \
  -    CPSMatchConfidence, BetterCommonPlayInterface, CPSTrackStatus
  -from ovos_workshop.frameworks.cps.youtube import is_youtube, \
  +from ovos_workshop.frameworks import CPSMatchType, CPSPlayback, \
  +    CPSMatchConfidence, CommonPlayInterface as BetterCommonPlayInterface, CPSTrackStatus
  +from ovos_workshop.frameworks.playback.youtube import is_youtube, \
  ```
  - After doing so, I'm left with these errors:

  ```
  2021-08-03 12:58:47.491 | ERROR    | 45630 | mycroft.skills.mycroft_skill.mycroft_skill:default_shutdown:1335 | Skill specific shutdown function encountered an error: AttributeError("'BetterPlaybackControlSkill' object has no attribute 'cps'")
  2021-08-03 12:58:47.500 | ERROR    | 45630 | mycroft.skills.mycroft_skill.mycroft_skill:default_shutdown:1360 | Failed to stop skill: BetterPlaybackControlSkill
  Traceback (most recent call last):
    File "mycroft-core/mycroft/skills/skill_loader.py", line 307, in _create_skill_instance
      self.instance.initialize()
    File "/opt/mycroft/skills/skill-better-playback-control.jarbasskills/__init__.py", line 26, in initialize
      self.cps = BetterCommonPlayInterface(
  TypeError: __init__() got an unexpected keyword argument 'backwards_compatibility'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "mycroft-core/mycroft/skills/mycroft_skill/mycroft_skill.py", line 1358, in default_shutdown
      self.stop()
    File "/opt/mycroft/skills/skill-better-playback-control.jarbasskills/__init__.py", line 35, in stop
      return self.cps.stop()
  AttributeError: 'BetterPlaybackControlSkill' object has no attribute 'cps'
  2021-08-03 12:58:47.502 | ERROR    | 45630 | mycroft.skills.skill_loader:_create_skill_instance:313 | Skill initialization failed with TypeError("__init__() got an unexpected keyword argument 'backwards_compatibility'")
  Traceback (most recent call last):
    File "mycroft-core/mycroft/skills/skill_loader.py", line 307, in _create_skill_instance
      self.instance.initialize()
    File "/opt/mycroft/skills/skill-better-playback-control.jarbasskills/__init__.py", line 26, in initialize
      self.cps = BetterCommonPlayInterface(
  TypeError: __init__() got an unexpected keyword argument 'backwards_compatibility'
  2021-08-03 12:58:47.505 | ERROR    | 45630 | mycroft.skills.skill_loader:_communicate_load_status:351 | Skill skill-better-playback-control.jarbasskills failed to load
  ```-->

**Comment by theCalcaholic** [comment]
As I erroneously assumed that multiple skills were broken, this issue is now basically reduced to the reminder that the requirements aren't all available on pipy at the moment :)

Fee free to close it at any time

**Comment by JarbasAl** [comment]
essentially every skill in this list needs to be checked and possibly updated to latest imports/pkg versions https://www.pling.com/c/1489798/

please open issues in the individual repos for skills, or https://github.com/OpenVoiceOS/skill-better-playback-control if it affects several skills. I expect most time will be a simple change of imports and requirements.txt, hopefully this was the last time the imports changed and it should be easier to keep things in sync moving forward

**Comment by JarbasAl** [comment]
> So, in order to comply to the new requirements.txt, I installed ovos-workshop from master (because 0.0.3a1 is not available on pipy yet).
> 
published on pipy

**Comment by theCalcaholic** [comment]
Just to let you know: Issues are disabled on https://github.com/OpenVoiceOS/skill-better-playback-control, otherwise that would have been my first idea as well :)

**Comment by JarbasAl** [comment]
> Just to let you know: Issues are disabled on [OpenVoiceOS/skill-better-playback-control](https://github.com/OpenVoiceOS/skill-better-playback-control), otherwise that would have been my first idea as well :)

oops, that was an oversight, i think they are enabled now, thanks for the ping
